include:
  - 'https://raw.githubusercontent.com/JuliaGPU/gitlab-ci/master/templates/v6.yml'

image: nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04


# julia:1.0:
#   extends:
#     - .julia:1.0
#     - .test
#   tags:
#     - nvidia
# 
# julia:1.1:
#   extends:
#     - .julia:1.1
#     - .test
#   tags:
#     - nvidia
# 
# julia:1.2:
#   extends:
#     - .julia:1.2
#     - .test
#   tags:
#     - nvidia

julia:1.4:
  extends:
    - .julia:1.4
    - .test
  tags:
    - nvidia

julia:nightly:
  extends:
    - .julia:nightly
    - .test
  tags:
    - nvidia
  allow_failure: true
