# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.7
  - 1.0
  - nightly
# uncomment the following lines to override the default test script
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("Flux"); Pkg.test("Flux"; coverage=true)'
matrix:
  allow_failures:
    - julia: nightly
after_success:
  - julia -e 'using Pkg; ps=Pkg.PackageSpec(name="Documenter", version="0.19"); Pkg.add(ps); Pkg.pin(ps); Pkg.add("NNlib")'
  - julia -e 'using Pkg; cd(Pkg.dir("Flux")); include(joinpath("docs", "make.jl"))'
